name: "Update"
description: "Set Env keys to Terraform Cloud"
inputs:
  TF_API_TOKEN:
    description: "TF_API_TOKEN Key"
    required: true
  TF_WORKSPACE_ID:
    description: "TF_WORKSPACE_ID"
    required: true
  AWS_ACCESS_KEY_ID:
    description: "aws-access-key-id"
  AWS_SECRET_ACCESS_KEY:
    description: "aws-secret-access-key"
runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Action Checkout
      uses: actions/checkout@v3

    - name: Get file from S3
      run: aws s3 cp s3://testbucketwithterraform/test.env /path/on/local/machine
      shell: bash

    - name: Update Keys
      run: |
        while IFS='=' read -r key value; do
          curl \
            --header "Authorization: Bearer ${{ inputs.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data "{\"data\":{\"attributes\":{\"key\":\"$key\",\"value\":\"$value\",\"category\":\"terraform\",\"description\":null,\"hcl\":true,\"sensitive\":false,\"read-only\":false,\"created-at\":null},\"relationships\":{\"configurable\":{\"data\":{\"type\":\"workspaces\",\"id\":\"${{ inputs.TF_WORKSPACE_ID }}\"}}},\"type\":\"vars\"}}" \
            https://app.terraform.io/api/v2/workspaces/${{ inputs.TF_WORKSPACE_ID }}/vars
        done </path/on/local/machine
      shell: bash
